name = "discordhook"
main = "index.js"
compatibility_date = "2025-07-13"

[vars]
# The necessary secrets are:
# - DISCORD_WEBHOOK_URL
# You can set this to forward to an address as well
# - FORWARD_TO_ADDRESS

# OBS/Logs is billable, but gives you logs on errors sending to Discord/etc
#[observability.logs]
#enabled = true
